repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.9.0
    hooks:
      - id: eslint
        additional_dependencies: ['eslint', 'eslint-plugin-vue']
        files: ^src/client/.*\.(js|vue)$

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        files: ^src/server/.*\.py$
