sparql_endpoint_url: "http://190.92.134.58:8890/sparql"
batch_size: 10000
log_level: "DEBUG" # Options: DEBUG, INFO, WARNING (DEFAULT), ERROR, CRITICAL
query_source: |
  SELECT DISTINCT ?id ?predicate ?object ?g
  WHERE {
    GRAPH ?g {
      ?id ?predicate ?object .
    }
    FILTER(?g IN (<http://data.15926.org/rdl>, <http://data.15926.org/dm>, <http://data.15926.org/coco>))
  }

