site_name: ISO 15926-4 Visualiser


theme:
  name: material
  features:
    - navigation.tabs


nav:
  - Overview: index.md
  - Developer:
      - Introduction: developer/index.md
  - Maintainer: 
      - Introduction: maintainer/index.md
  - Administrator: 
      - Introduction: administrator/index.md
  - Changelog: 
      - Introduction: changelog/index.md

