site_name: Iso15926Visualiser Documentation
copyright: System Health Lab
repo_url: https://github.com/nlp-tlp/15926-4-RDL-CITS3200

theme:
    name: material
    features:
        - navigation.tabs

nav:
    - Overview: index.md
    - Developer:
          - Introduction: developer/index.md
          - Tech stack: developer/tech_stack.md
          - Developer setup: developer/deverloper_setup.md
          - CI/CD: developer/cicd.md
    - Maintainer:
          - Introduction: maintainer/index.md
          - Accessing production: maintainer/using_instance.md
          - Migrating production: maintainer/migrating_instance.md
    - Administrator:
          - Introduction: administrator/index.md
    - Changelog:
          - Introduction: changelog/index.md
