site_name: Iso15926Visualiser Documentation
copyright: System Health Lab
repo_url: https://github.com/nlp-tlp/15926-4-RDL-CITS3200

theme:
    name: material
    features:
        - navigation.tabs

extra:
  extra_head: |
    <link rel="apple-touch-icon" sizes="180x180" href="img/apple-touch-icon.png" />
    <link rel="icon" type="image/png" sizes="16x16" href="img/favicon-16x16.png" />
    <link rel="icon" type="image/png" sizes="32x32" href="img/favicon-32x32.png" />
    <link rel="icon" type="image/png" sizes="192x192" href="img/android-chrome-192x192.png" />
    <link rel="icon" type="image/png" sizes="512x512" href="img/android-chrome-512x512.png" />
    <link rel="shortcut icon" href="img/favicon.ico" />

nav:
    - Overview: index.md
    - Developer:
          - Introduction: developer/index.md
          - Tech stack: developer/tech_stack.md
          - Developer setup: developer/developer_setup.md
          - CI/CD: developer/cicd.md
    - Maintainer:
          - Introduction: maintainer/index.md
          - Accessing production: maintainer/using_instance.md
          - Migrating production: maintainer/migrating_instance.md
          - Maintaining SSL Certificate: maintainer/ssl_cert.md
    - Administrator:
          - Introduction: administrator/index.md
    - Changelog:
          - Introduction: changelog/index.md
