services:
    client:
        image: myclient
        container_name: Client
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.client.rule=PathPrefix(`/`)"
            - "traefik.http.routers.client.entrypoints=websecure"
        ports:
            - "${CLIENT_PORT:-5173}:5173"
        env_file:
            - .env.production

    server:
        image: myserver
        container_name: Server
        ports:
            - "${SERVER_PORT:-5000}:5000"
        volumes:
            - db-data:/app/db
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.server.rule=PathPrefix(`/node`) || PathPrefix(`/search`)"
            - "traefik.http.routers.server.entrypoints=websecure"
        environment:
            - FLASK_ENV=production
            - FLASK_APP=${FLASK_APP:-server.py}

    traefik:
        image: "traefik:v3.1"
        container_name: Traefik
        command:
            - "--log.level=INFO"
            - "--api.insecure=false"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entryPoints.web.address=:80"
            - "--entryPoints.websecure.address=:443"
            - "--entryPoints.websecure.http.tls=true"  # Enable TLS for websecure
            - "--providers.file.filename=/certs/tls.yml"  # Use the TLS file provider
        labels:
            - "traefik.http.routers.traefik-secure.tls.domains[0].main=iso15926vis.org"
            - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.iso15926vis.org"
        ports:
            - "80:80" # HTTP
            - "443:443" # HTTPS
            - "8080:8080" # Traefik Dashboard
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "/home/ubuntu/certs:/certs" # SSL certificate directory

volumes:
    db-data: # Yes nothing below this line
