version: '3'
services:
  client:
    build: ./client
    ports:
      - "${CLIENT_PORT:-5173}:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}

  server:
    build: ./server
    ports:
      - "${SERVER_PORT:-5000}:5000"
    volumes:
      - ./server:/app
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_APP=${FLASK_APP:-server.py}
