services:
  client:
    build: ./client
    container_name: Client
    ports:
      - "${CLIENT_PORT:-5173}:5173"
    volumes:
      - ./client:/app
      - /app/node_modules # Use seperate node modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}

  server:
    build: ./server
    container_name: Server
    ports:
      - "${SERVER_PORT:-5000}:5000"
    volumes:
      - ./server:/app
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_APP=${FLASK_APP:-server.py}

  # mkdocs:
  #   build: ../docs
  #   ports:
  #     - "${MKDOCS_PORT:-8001}:8000"
  #   volumes:
  #     - ../docs:/docs