services:
    client:
        build: ./client
        container_name: Client
        ports:
            - "80:80" # nginx will expose port 80 to serve both the client and API
        env_file:
            - .env

    server:
        build: ./server
        container_name: Server
        expose: # Not available publicly
            - "${SERVER_PORT:-5000}:5000"
        volumes:
            - db-data:/app/db
        environment:
            - FLASK_ENV=production
            - FLASK_APP=${FLASK_APP:-server.py}

volumes:
    db-data: # Yes nothing below this line
