services:
    client:
        build: ./client
        container_name: Client
        ports:
            - "${CLIENT_PORT:-5173}:5173"
        environment:
            - NODE_ENV=production

    server:
        build: ./server
        container_name: Server
        ports:
            - "${SERVER_PORT:-5000}:5000"
        volumes:
            - ./db:/db
        environment:
            - FLASK_ENV=production
