name: Run Client Tests (Vue)

on:
    push:
        branches:
            - main
            - "**"
    pull_request:
        branches:
            - main
            - "**"
    workflow_dispatch:

jobs:
    test:
        name: Run Tests with Vitest
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install dependencies
              run: |
                  cd src/client
                  npm ci
                  npx playwright install --with-deps

            - name: Run unit tests
              run: |
                  cd src/client
                  npm run test:unit

            - name: Run e2e tests
              run: |
                  cd src/client
                  npm run test:e2e
